### ISSUE TITLE
Suggestion: Avoid using code snippets that cannot be copied into the REPL and run right away

### ISSUE THREAD

**Issue by dadepo** [marick/static-fp#3]
For example the following code snippet in Chapter on function:

```
model
|> forgetHistoryPage history.id -- produces a new version of `model`
|> addCmd (Navigation.toPageChangeCmd next)
```

This cannot be copied right away into the REPL because all the functions and values included in that snippet is assumed to have been defined or imported somewhere else. I think this has a negative impact on the flow of reading the book and being able to try the code snippets out and tinker with it.

**Comment by marick** [comment]
Most of them are (should be). I'll try to make more of them be that way.
